#!/usr/bin/env python3
"""SIH Scenario 2: physics-enabled chaotic Indian urban junction for CARLA 0.9.15.

Depicts a busy Indian road: pedestrians and cattle can step onto the road at
almost any moment -- including right as the ego vehicle is about to reach
them -- small potholes/debris litter the lanes, and traffic overtakes from
BOTH the left and right, sometimes cutting back in sharply. A fast bike is
liable to suddenly race past the ego, and is extra likely to do so exactly
while the ego is turning through the junction.

Vehicles use CARLA physics and Traffic Manager. They are held with a brake
and released in a controlled sequence; they are never moved with
set_transform(). Pedestrians use controller.ai.walker, so their walking
animation is generated by CARLA. The pushcart remains a static obstacle by
design. "Cattle" are represented with pedestrian walker blueprints (CARLA
0.9.15 ships no animal meshes) but are logically tagged and behave like
livestock ambling into the road.
"""
from __future__ import annotations

import json
import argparse
import csv
import math
import queue
import random
import threading
import time
from pathlib import Path
from typing import Any

import carla
import cv2
import httpx
import numpy as np

TOWN = "Town05"
DT = 0.05
M2_URL = "http://127.0.0.1:8000/api/v1/perception"
TM_PORT = 8001
LOG_DIR = Path("logs")
SENSOR_ID = "carla-scenario2-ego"
SENSOR_WAIT_S = 0.5
UPLOAD_QUEUE_SIZE = 4
SCENARIO_WARMUP_S = 5.0
JUNCTION_SEARCH_MAX_M = 80.0
JUNCTION_TRIGGER_DISTANCE_M = 32.0
JAYWALK_TRIGGER_DISTANCE_M = 12.0
QUEUE_SPACING_M = 14.0
FIRST_QUEUE_BACKOFF_M = 18.0
MIN_SPAWN_SEPARATION_M = 10.0
RELEASE_INTERVAL_S = 2.5
CROSS_CLEAR_TIME_S = 7.0
WEAVE_TRIGGER_DISTANCE_M = 35.0
WEAVE_PERIOD_S = 2.5
WEAVE_SPEED_KPH = 55.0  # a bike "racing by" should actually be fast
PUSHCART_BACKOFF_M = 30.0
WALKER_MAX_SPEED_MPS = 1.35
WALKER_TARGET_RETRIES = 20
RANDOM_SEED = 2026

# --- continuous jaywalking (people can step out anywhere, anytime) ---
JAYWALK_SPAWN_INTERVAL_MIN_S = 3.0
JAYWALK_SPAWN_INTERVAL_MAX_S = 6.0
JAYWALK_AHEAD_MIN_M = 8.0
JAYWALK_AHEAD_MAX_M = 25.0
JAYWALK_SUDDEN_CHANCE = 0.35        # fraction that step out right as the car arrives
JAYWALK_SUDDEN_MIN_M = 6.0
JAYWALK_SUDDEN_MAX_M = 10.0
JAYWALK_MAX_ACTIVE = 6
JAYWALK_LIFETIME_S = 12.0
JAYWALK_DESPAWN_BEHIND_M = 20.0

# --- continuous cattle crossings ---
CATTLE_SPAWN_INTERVAL_MIN_S = 8.0
CATTLE_SPAWN_INTERVAL_MAX_S = 14.0
CATTLE_MAX_ACTIVE_GROUPS = 2
CATTLE_GROUP_SIZE = 3
CATTLE_LIFETIME_S = 25.0
CATTLE_TRIGGER_DISTANCE_M = 12.0

# --- potholes / road debris (kept small and sparse) ---
POTHOLE_COUNT = 25
POTHOLE_SEARCH_RADIUS_M = 90.0

# --- aggressive overtaking from both sides ---
OVERTAKE_GAP_TRIGGER_M = 30.0
OVERTAKE_RETRIGGER_MIN_S = 6.0
OVERTAKE_RETRIGGER_MAX_S = 10.0

# --- sudden high-speed bike racers, extra likely mid-turn ---
RACER_SPAWN_COOLDOWN_MIN_S = 5.0
RACER_SPAWN_COOLDOWN_MAX_S = 9.0
RACER_BEHIND_MIN_M = 25.0
RACER_BEHIND_MAX_M = 45.0
RACER_SPEED_DIFFERENCE = -60.0  # negative => faster than the speed limit
RACER_TURN_BONUS_CHANCE = 0.6
RACER_TURN_COOLDOWN_SCALE = 0.4
RACER_LIFETIME_S = 15.0
RACER_STEER_TURNING_THRESHOLD = 0.12

# --- ego stuck-after-collision recovery (no M5 exists yet to slow/stop the
# ego ahead of a predicted conflict, so it's expected to collide -- but it
# must not stay permanently wedged against an obstacle). A sustained
# collision pileup was observed to destabilize the CARLA server itself in
# live testing, so this window is kept short -- recover fast, don't let a
# pileup linger. ---
EGO_STUCK_DURATION_S = 2.5
EGO_STUCK_DISPLACEMENT_M = 1.5  # net movement over EGO_STUCK_DURATION_S below this counts as stuck
EGO_RESPAWN_AHEAD_M = 20.0

# --- continuous cross-vehicle respawning (mirrors the jaywalker pattern
# above) so the junction stays busy well past the original one-shot roster
# on a run longer than ~20s ---
CROSS_VEHICLE_MAX_ACTIVE = 8  # lowered from 13: sustained multi-actor collision pileups at the
                               # higher count correlated with CARLA engine crashes in live testing
CROSS_VEHICLE_RESPAWN_MIN_S = 4.0
CROSS_VEHICLE_RESPAWN_MAX_S = 8.0
CROSS_VEHICLE_DESPAWN_BEHIND_M = 60.0

CAMERA_TRANSFORM = carla.Transform(carla.Location(x=1.5, z=2.2), carla.Rotation(pitch=-5.0))
LIDAR_TRANSFORM = carla.Transform(carla.Location(z=2.3))
RADAR_TRANSFORM = carla.Transform(carla.Location(x=2.0, z=1.2))

CARS = [
    "vehicle.carlamotors.carlacola", "vehicle.volkswagen.t2",
    "vehicle.mini.cooper_s", "vehicle.nissan.micra",
    "vehicle.toyota.prius", "vehicle.audi.a2",
]
BIKES = [
    "vehicle.vespa.zx125", "vehicle.yamaha.yzf", "vehicle.kawasaki.ninja",
    "vehicle.harley-davidson.low_rider", "vehicle.diamondback.century",
    "vehicle.bh.crossbike", "vehicle.gazelle.omafiets",
]


class FrameBuffer:
    def __init__(self, name: str, max_frames: int = 32):
        self.name = name
        self.frames: dict[int, Any] = {}
        self.cv = threading.Condition()
        self.max_frames = max_frames

    def put(self, frame: int, data: Any) -> None:
        with self.cv:
            self.frames[int(frame)] = data
            while len(self.frames) > self.max_frames:
                self.frames.pop(min(self.frames))
            self.cv.notify_all()

    def get(self, frame: int, timeout: float) -> Any:
        deadline = time.monotonic() + timeout
        with self.cv:
            while int(frame) not in self.frames:
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    raise TimeoutError(f"{self.name} frame {frame} not received")
                self.cv.wait(remaining)
            return self.frames.pop(int(frame))


class Uploader:
    def __init__(self, url: str):
        self.url = url
        self.q: queue.Queue[dict[str, Any] | None] = queue.Queue(UPLOAD_QUEUE_SIZE)
        self.stop_event = threading.Event()
        self.sent = self.failed = self.dropped = 0
        self.thread = threading.Thread(target=self._run, daemon=True)
        self.thread.start()

    def submit(self, packet: dict[str, Any]) -> None:
        try:
            self.q.put_nowait(packet)
        except queue.Full:
            try:
                self.q.get_nowait()
                self.dropped += 1
                self.q.put_nowait(packet)
            except queue.Empty:
                self.dropped += 1

    def _run(self) -> None:
        with httpx.Client(timeout=5.0) as client:
            while not self.stop_event.is_set():
                try:
                    packet = self.q.get(timeout=0.2)
                except queue.Empty:
                    continue
                if packet is None:
                    return
                frame = packet["frame"]
                files = {
                    "image": (f"rgb_{frame}.png", packet["image"], "image/png"),
                    "lidar_file": (f"lidar_{frame}.bin", packet["lidar"], "application/octet-stream"),
                    "radar_file": (f"radar_{frame}.bin", packet["radar"], "application/octet-stream"),
                }
                data = {
                    "sensor_id": SENSOR_ID,
                    "frame_id": str(frame),
                    "timestamp": repr(packet["timestamp"]),
                    "ego_speed_mps": repr(packet["speed"]),

                    "ego_position": json.dumps(packet["ego_position"]),
                    "ego_velocity": json.dumps(packet["ego_velocity"]),
                    "ego_yaw_deg": repr(packet["ego_yaw_deg"]),
                }
                try:
                    client.post(self.url, data=data, files=files).raise_for_status()
                    self.sent += 1
                except (httpx.HTTPError, OSError) as exc:
                    self.failed += 1
                    print(f"[M2][WARN] frame={frame}: {exc}", flush=True)

    def close(self) -> None:
        self.stop_event.set()
        try:
            self.q.put_nowait(None)
        except queue.Full:
            pass
        self.thread.join(timeout=6.0)


class Scenario2:
    def __init__(self, host: str, port: int, ego_index: int, m2_url: str, tm_port: int):
        self.host, self.port, self.ego_index = host, port, ego_index
        self.m2_url, self.tm_port = m2_url, tm_port
        self.client = self.world = self.map = self.tm = None
        self.bp = None
        self.ego = self.collision_sensor = None
        self.rgb = self.lidar = self.radar = None
        self.rgb_buf, self.lidar_buf, self.radar_buf = FrameBuffer("RGB"), FrameBuffer("LiDAR"), FrameBuffer("Radar")
        self.uploader: Uploader | None = None
        self.junction = self.ego_entry_wp = None
        self.lights: list[Any] = []
        self.cross: list[dict[str, Any]] = []
        self.lane_traffic: list[dict[str, Any]] = []
        self.overtaker = None
        self.walkers: list[dict[str, Any]] = []
        self.controllers: list[Any] = []
        self.weave_bike = self.pushcart = None
        self.static_props: list[Any] = []
        self.cattle: list[dict[str, Any]] = []
        self.racers: list[dict[str, Any]] = []
        self.weave_triggered = False
        self.weave_elapsed = 0.0
        self.cross_armed = False
        self.sim_time = 0.0
        self.frame_count = 0
        self.collisions: list[dict[str, Any]] = []
        self.trajectory: list[dict[str, Any]] = []
        self.next_jaywalk_time = 0.0
        self.next_cattle_time = 0.0
        self.next_racer_time = 0.0
        self.next_cross_vehicle_time = 0.0
        self.ego_stuck_anchor: tuple[float, carla.Location] | None = None

    def setup(self) -> None:
        random.seed(RANDOM_SEED)
        self.client = carla.Client(self.host, self.port)
        self.client.set_timeout(10.0)
        self.world = self.client.load_world(TOWN)
        settings = self.world.get_settings()
        settings.synchronous_mode = True
        settings.fixed_delta_seconds = DT
        settings.max_substep_delta_time = 0.01
        settings.max_substeps = 5
        self.world.apply_settings(settings)
        self.tm = self.client.get_trafficmanager(self.tm_port)
        self.tm.set_synchronous_mode(True)
        self.tm.set_global_distance_to_leading_vehicle(8.0)
        self.map = self.world.get_map()
        bp = self.world.get_blueprint_library()
        self.bp = bp
        spawns = self.map.get_spawn_points()
        if not 0 <= self.ego_index < len(spawns):
            raise ValueError(f"Invalid ego spawn index {self.ego_index}; available={len(spawns)}")
        ego_bp = bp.find("vehicle.tesla.model3")
        ego_bp.set_attribute("role_name", "ego_vehicle")
        self.ego = self.world.spawn_actor(ego_bp, spawns[self.ego_index])
        self._setup_sensors(bp)
        self.junction, self.ego_entry_wp = self._find_junction(spawns[self.ego_index])
        if self.junction is None:
            raise RuntimeError("No junction found ahead; select another --ego-spawn-index")
        self._freeze_lights()
        self._spawn_cross_vehicles(bp)
        self._spawn_same_lane_traffic(bp, spawns[self.ego_index])
        self._spawn_walkers(bp)
        self._spawn_cattle(bp)
        self._spawn_pushcart(bp)
        self._spawn_weave_bike(bp)
        self._spawn_potholes(bp)
        # continuous chaos scheduling -- staggered so nothing fires on the same tick
        self.next_jaywalk_time = SCENARIO_WARMUP_S + random.uniform(1.0, 3.0)
        self.next_cattle_time = SCENARIO_WARMUP_S + random.uniform(3.0, 6.0)
        self.next_racer_time = SCENARIO_WARMUP_S + random.uniform(2.0, 5.0)
        self.next_cross_vehicle_time = SCENARIO_WARMUP_S + CROSS_CLEAR_TIME_S + random.uniform(2.0, 5.0)
        self.uploader = Uploader(self.m2_url)
        print(f"[SETUP] junction={self.junction.id} cross={len(self.cross)} walkers={len(self.walkers)} "
              f"cattle={len(self.cattle)} controllers={len(self.controllers)} "
              f"weave_bike={'yes' if self.weave_bike else 'no'} potholes={len(self.static_props)}", flush=True)

    def _setup_sensors(self, bp) -> None:
        cam = bp.find("sensor.camera.rgb")
        cam.set_attribute("image_size_x", "1280"); cam.set_attribute("image_size_y", "720")
        # Widened from 90 to 150 deg -- see M1_Pipeline/common.py's
        # setup_ego_sensors for the full rationale (live-testing finding:
        # 70% of LiDAR-tracked objects fell outside a 90 deg forward cone).
        # M3_Pipeline/config.py's CAMERA_FOV_DEG MUST mirror this.
        cam.set_attribute("fov", "150"); cam.set_attribute("sensor_tick", str(DT))
        self.rgb = self.world.spawn_actor(cam, CAMERA_TRANSFORM, attach_to=self.ego)
        self.rgb.listen(lambda x: self.rgb_buf.put(x.frame, x))
        lidar = bp.find("sensor.lidar.ray_cast")
        lidar.set_attribute("channels", "32"); lidar.set_attribute("range", "80")
        lidar.set_attribute("points_per_second", "640000"); lidar.set_attribute("rotation_frequency", str(1.0 / DT))
        lidar.set_attribute("upper_fov", "10"); lidar.set_attribute("lower_fov", "-30"); lidar.set_attribute("sensor_tick", str(DT))
        self.lidar = self.world.spawn_actor(lidar, LIDAR_TRANSFORM, attach_to=self.ego)
        self.lidar.listen(lambda x: self.lidar_buf.put(x.frame, bytes(x.raw_data)))
        radar = bp.find("sensor.other.radar")
        radar.set_attribute("horizontal_fov", "35"); radar.set_attribute("vertical_fov", "20")
        radar.set_attribute("range", "80"); radar.set_attribute("points_per_second", "1500"); radar.set_attribute("sensor_tick", str(DT))
        self.radar = self.world.spawn_actor(radar, RADAR_TRANSFORM, attach_to=self.ego)
        self.radar.listen(lambda x: self.radar_buf.put(x.frame, bytes(x.raw_data)))
        cbp = bp.find("sensor.other.collision")
        self.collision_sensor = self.world.spawn_actor(cbp, carla.Transform(), attach_to=self.ego)
        self.collision_sensor.listen(self._on_collision)

    def _find_junction(self, tf):
        wp = self.map.get_waypoint(tf.location)
        travelled = 0.0
        previous = wp
        while travelled < JUNCTION_SEARCH_MAX_M:
            nxt = wp.next(2.0)
            if not nxt: return None, None
            wp = nxt[0]; travelled += 2.0
            if wp.is_junction: return wp.get_junction(), previous
            previous = wp
        return None, None

    def _freeze_lights(self) -> None:
        try:
            junction_lights = list(self.world.get_traffic_lights_in_junction(self.junction.id))
        except AttributeError:
            junction_lights = []
        all_lights = list(self.world.get_actors().filter("traffic.traffic_light*"))
        self.lights = list({l.id: l for l in (junction_lights + all_lights)}.values())
        for light in self.lights:
            light.set_state(carla.TrafficLightState.Green)
            light.freeze(True)

    def _candidate_approaches(self):
        result, keys = [], set()
        for entry, exit_wp in self.junction.get_waypoints(carla.LaneType.Driving):
            if self.ego_entry_wp and entry.road_id == self.ego_entry_wp.road_id:
                continue
            key = (entry.road_id, entry.lane_id)
            if key in keys: continue
            if any(entry.transform.location.distance(x[0].transform.location) < 12.0 for x in result):
                continue
            keys.add(key); result.append((entry, exit_wp))
        return result

    def _spawn_cross_vehicles(self, bp) -> None:
        approaches = self._candidate_approaches()
        if not approaches:
            print("[SETUP][WARN] no cross approaches", flush=True); return
        roster = [(name, False) for name in CARS] + [(name, True) for name in BIKES]
        random.shuffle(roster)
        reserved: list[carla.Location] = []
        for index, (name, is_bike) in enumerate(roster):
            entry, exit_wp = approaches[index % len(approaches)]
            slot = index // len(approaches)
            spawn_list = entry.previous(FIRST_QUEUE_BACKOFF_M + slot * QUEUE_SPACING_M)
            if not spawn_list: continue
            tf = spawn_list[0].transform
            if is_bike:
                right = tf.get_right_vector(); side = random.uniform(-0.7, 0.7)
                tf.location.x += right.x * side; tf.location.y += right.y * side
            tf.location.z += 0.3
            if any(tf.location.distance(x) < MIN_SPAWN_SEPARATION_M for x in reserved):
                continue
            vehicle_bp = bp.find(name)
            vehicle_bp.set_attribute("role_name", "physics_cross_traffic")
            actor = self.world.try_spawn_actor(vehicle_bp, tf)
            if actor is None:
                print(f"[SETUP][WARN] failed spawn {name} slot={slot}", flush=True); continue
            reserved.append(carla.Location(tf.location.x, tf.location.y, tf.location.z))
            actor.set_simulate_physics(True)
            actor.set_enable_gravity(True)
            actor.set_autopilot(True, self.tm_port)
            self.tm.ignore_lights_percentage(actor, 100.0)
            self.tm.ignore_signs_percentage(actor, 100.0)
            self.tm.auto_lane_change(actor, True)
            self.tm.random_left_lanechange_percentage(actor, 20.0)
            self.tm.random_right_lanechange_percentage(actor, 20.0)
            # Relaxed collision avoidance + varied speed so crossing paths at
            # the junction produce real collision chances instead of the TM
            # cleanly avoiding every conflict (default ignore_vehicles=0%).
            self.tm.ignore_vehicles_percentage(actor, random.uniform(35.0, 65.0))
            self.tm.vehicle_percentage_speed_difference(actor, random.uniform(-10.0, 35.0))
            self.tm.distance_to_leading_vehicle(actor, 2.0)
            actor.apply_control(carla.VehicleControl(throttle=0.0, brake=1.0, hand_brake=True))
            self.cross.append({"actor": actor, "entry": entry, "exit": exit_wp,
                               "release_time": None, "released": False, "start": carla.Location(tf.location.x, tf.location.y, tf.location.z)})
            print(f"[SETUP] physics vehicle actor={actor.id} type={name} at=({tf.location.x:.1f},{tf.location.y:.1f})", flush=True)

    def _walker_nav_target(self, origin: carla.Location, preferred: carla.Location) -> carla.Location | None:
        """Return a reachable navigation-mesh target for controller.ai.walker."""
        best = None
        best_error = float("inf")
        for _ in range(WALKER_TARGET_RETRIES):
            candidate = self.world.get_random_location_from_navigation()
            if candidate is None:
                continue
            distance = origin.distance(candidate)
            error = candidate.distance(preferred)
            if 5.0 <= distance <= 35.0 and error < best_error:
                best, best_error = candidate, error
        return best

    def _is_behind_ego(self, loc: carla.Location) -> bool:
        if not self.ego or not self.ego.is_alive:
            return False
        tf = self.ego.get_transform()
        forward = tf.get_forward_vector()
        to_actor = loc - tf.location
        return (forward.x * to_actor.x + forward.y * to_actor.y) < 0.0

    def _is_ego_turning(self) -> bool:
        """True while the ego is actively steering or inside/near the junction."""
        if not self.ego or not self.ego.is_alive:
            return False
        steer = abs(self.ego.get_control().steer)
        ego_wp = self.map.get_waypoint(self.ego.get_location())
        near_junction = bool(ego_wp and ego_wp.is_junction) or (
            self.junction is not None
            and self.ego.get_location().distance(self.junction.bounding_box.location) < JUNCTION_TRIGGER_DISTANCE_M
        )
        return steer > RACER_STEER_TURNING_THRESHOLD or near_junction

    # ------------------------------------------------------------------
    # Initial (pre-placed) pedestrians / cattle -- the first wave, present
    # from the start so the road already feels busy.
    # ------------------------------------------------------------------
    def _spawn_walkers(self, bp) -> None:
        walker_bps = bp.filter("walker.pedestrian.*")
        controller_bp = bp.find("controller.ai.walker")
        if not walker_bps or controller_bp is None or not self.ego_entry_wp: return
        for i in range(15):
            back = self.ego_entry_wp.previous(5.0 + i * 4.0)
            wp = back[0] if back else self.ego_entry_wp
            right = wp.transform.get_right_vector()
            side = random.choice([-1, 1]) * random.uniform(1.8, 2.5)
            tf = carla.Transform(carla.Location(wp.transform.location.x + right.x * side,
                                                 wp.transform.location.y + right.y * side,
                                                 wp.transform.location.z + 0.5), wp.transform.rotation)
            walker = self.world.try_spawn_actor(random.choice(walker_bps), tf)
            if walker is None: continue
            preferred = carla.Location(tf.location.x - right.x * side * 2.0,
                                       tf.location.y - right.y * side * 2.0, tf.location.z)
            target = self._walker_nav_target(tf.location, preferred)
            if target is None:
                walker.destroy()
                continue
            controller = self.world.spawn_actor(controller_bp, carla.Transform(), attach_to=walker)
            controller.start()
            controller.go_to_location(target)
            controller.set_max_speed(0.0)
            self.walkers.append({"actor": walker, "controller": controller, "target": target,
                                  "started": False, "spawn_time": 0.0, "sudden": False})
            self.controllers.append(controller)

    def _spawn_cattle(self, bp) -> None:
        walker_bps = bp.filter("walker.pedestrian.*")
        controller_bp = bp.find("controller.ai.walker")
        if not walker_bps or controller_bp is None or not self.ego_entry_wp: return
        for dist in [35.0, 65.0]:
            back = self.ego_entry_wp.previous(dist)
            wp = back[0] if back else self.ego_entry_wp
            right = wp.transform.get_right_vector()
            for i in range(3):
                side = 2.2 + random.uniform(-0.5, 0.5)
                tf = carla.Transform(carla.Location(wp.transform.location.x + right.x * side + random.uniform(-1, 1),
                                                     wp.transform.location.y + right.y * side + random.uniform(-1, 1),
                                                     wp.transform.location.z + 0.5), wp.transform.rotation)
                walker = self.world.try_spawn_actor(random.choice(walker_bps), tf)
                if walker is None: continue
                preferred = carla.Location(tf.location.x - right.x * side * 2.5,
                                           tf.location.y - right.y * side * 2.5, tf.location.z)
                target = self._walker_nav_target(tf.location, preferred)
                if target:
                    controller = self.world.spawn_actor(controller_bp, carla.Transform(), attach_to=walker)
                    controller.start()
                    controller.go_to_location(target)
                    controller.set_max_speed(0.0)
                    self.cattle.append({"actor": walker, "controller": controller, "target": target,
                                         "started": False, "spawn_time": 0.0})
                    self.controllers.append(controller)

    # ------------------------------------------------------------------
    # Continuous jaywalking / cattle spawners -- fire throughout the run so
    # people and animals can appear "anytime, anywhere", including right in
    # front of the ego.
    # ------------------------------------------------------------------
    def _spawn_dynamic_jaywalker(self) -> None:
        walker_bps = self.bp.filter("walker.pedestrian.*")
        controller_bp = self.bp.find("controller.ai.walker")
        if not walker_bps or controller_bp is None or not self.ego or not self.ego.is_alive:
            return
        ego_wp = self.map.get_waypoint(self.ego.get_location(), project_to_road=True, lane_type=carla.LaneType.Driving)
        if ego_wp is None:
            return
        sudden = random.random() < JAYWALK_SUDDEN_CHANCE
        ahead = random.uniform(JAYWALK_SUDDEN_MIN_M, JAYWALK_SUDDEN_MAX_M) if sudden \
            else random.uniform(JAYWALK_AHEAD_MIN_M, JAYWALK_AHEAD_MAX_M)
        route = ego_wp.next(ahead)
        if not route:
            return
        wp = route[0]
        right = wp.transform.get_right_vector()
        side = random.choice([-1, 1])
        start_offset = side * random.uniform(3.0, 5.0)
        spawn_tf = carla.Transform(carla.Location(
            wp.transform.location.x + right.x * start_offset,
            wp.transform.location.y + right.y * start_offset,
            wp.transform.location.z + 0.5), wp.transform.rotation)
        walker = self.world.try_spawn_actor(random.choice(walker_bps), spawn_tf)
        if walker is None:
            return
        target_offset = -side * random.uniform(3.0, 5.0)
        preferred = carla.Location(
            wp.transform.location.x + right.x * target_offset,
            wp.transform.location.y + right.y * target_offset,
            wp.transform.location.z)
        target = self._walker_nav_target(spawn_tf.location, preferred)
        if target is None:
            walker.destroy()
            return
        controller = self.world.spawn_actor(controller_bp, carla.Transform(), attach_to=walker)
        controller.start()
        controller.go_to_location(target)
        # sudden jaywalkers step out immediately; others linger like someone deciding to cross
        controller.set_max_speed(WALKER_MAX_SPEED_MPS * random.uniform(0.8, 1.6) if sudden else 0.0)
        self.walkers.append({"actor": walker, "controller": controller, "target": target,
                              "started": sudden, "spawn_time": self.sim_time, "sudden": sudden})
        self.controllers.append(controller)
        print(f"[RUNTIME] JAYWALK_SPAWN actor={walker.id} sudden={sudden} ahead={ahead:.1f}m side={side}", flush=True)

    def _maybe_spawn_jaywalker(self) -> None:
        if self.sim_time < self.next_jaywalk_time:
            return
        active = sum(1 for w in self.walkers if w["actor"].is_alive)
        if active < JAYWALK_MAX_ACTIVE:
            self._spawn_dynamic_jaywalker()
        self.next_jaywalk_time = self.sim_time + random.uniform(JAYWALK_SPAWN_INTERVAL_MIN_S, JAYWALK_SPAWN_INTERVAL_MAX_S)

    def _spawn_dynamic_cattle_group(self) -> None:
        walker_bps = self.bp.filter("walker.pedestrian.*")
        controller_bp = self.bp.find("controller.ai.walker")
        if not walker_bps or controller_bp is None or not self.ego or not self.ego.is_alive:
            return
        ego_wp = self.map.get_waypoint(self.ego.get_location(), project_to_road=True, lane_type=carla.LaneType.Driving)
        if ego_wp is None:
            return
        ahead = random.uniform(15.0, 35.0)
        route = ego_wp.next(ahead)
        if not route:
            return
        wp = route[0]
        right = wp.transform.get_right_vector()
        side = random.choice([-1, 1])
        spawned_ids = []
        for _ in range(CATTLE_GROUP_SIZE):
            offset = side * (2.0 + random.uniform(-0.4, 0.4)) + random.uniform(-1.0, 1.0)
            tf = carla.Transform(carla.Location(
                wp.transform.location.x + right.x * offset,
                wp.transform.location.y + right.y * offset,
                wp.transform.location.z + 0.5), wp.transform.rotation)
            walker = self.world.try_spawn_actor(random.choice(walker_bps), tf)
            if walker is None:
                continue
            preferred = carla.Location(
                tf.location.x - right.x * offset * 2.5,
                tf.location.y - right.y * offset * 2.5, tf.location.z)
            target = self._walker_nav_target(tf.location, preferred)
            if target is None:
                walker.destroy()
                continue
            controller = self.world.spawn_actor(controller_bp, carla.Transform(), attach_to=walker)
            controller.start()
            controller.go_to_location(target)
            controller.set_max_speed(0.0)
            self.cattle.append({"actor": walker, "controller": controller, "target": target,
                                 "started": False, "spawn_time": self.sim_time})
            self.controllers.append(controller)
            spawned_ids.append(walker.id)
        if spawned_ids:
            print(f"[RUNTIME] CATTLE_GROUP_SPAWN actors={spawned_ids} ahead={ahead:.1f}m", flush=True)

    def _maybe_spawn_cattle_group(self) -> None:
        if self.sim_time < self.next_cattle_time:
            return
        active = sum(1 for c in self.cattle if c["actor"].is_alive)
        active_groups = active // max(CATTLE_GROUP_SIZE, 1)
        if active_groups < CATTLE_MAX_ACTIVE_GROUPS:
            self._spawn_dynamic_cattle_group()
        self.next_cattle_time = self.sim_time + random.uniform(CATTLE_SPAWN_INTERVAL_MIN_S, CATTLE_SPAWN_INTERVAL_MAX_S)

    def _spawn_same_lane_traffic(self, bp, ego_tf) -> None:
        """Spawn visible traffic on the ego lane plus overtakers on BOTH sides."""
        ego_wp = self.map.get_waypoint(ego_tf.location, project_to_road=True,
                                        lane_type=carla.LaneType.Driving)
        if ego_wp is None:
            print("[SETUP][WARN] cannot find ego lane waypoint", flush=True)
            return
        # side is None for plain ahead/behind traffic; "left"/"right" marks
        # vehicles that will actively cut past the ego from that side.
        placements = [("ahead", 15.0, "vehicle.toyota.prius", 20.0, None),
                      ("ahead", 28.0, "vehicle.nissan.micra", 15.0, None),
                      ("ahead", 45.0, "vehicle.volkswagen.t2", 10.0, None),
                      ("behind", 15.0, "vehicle.mini.cooper_s", -5.0, None),
                      ("behind", 30.0, "vehicle.audi.a2", -15.0, None),
                      ("overtaker", 40.0, "vehicle.nissan.micra", -35.0, "left"),
                      ("overtaker", 50.0, "vehicle.harley-davidson.low_rider", -40.0, "right"),
                      ("overtaker", 60.0, "vehicle.yamaha.yzf", -45.0, "left"),
                      ("overtaker", 70.0, "vehicle.vespa.zx125", -40.0, "right")]
        reserved = [ego_tf.location]
        for direction, distance, name, speed_difference, side in placements:
            route = ego_wp.next(distance) if direction == "ahead" else ego_wp.previous(distance)
            if not route:
                continue
            tf = route[0].transform
            right = tf.get_right_vector()
            if side == "left":
                lane_offset = -3.5
            elif side == "right":
                lane_offset = 3.5
            else:
                lane_offset = 0.0
            tf.location.x += right.x * lane_offset
            tf.location.y += right.y * lane_offset
            tf.location.z += 0.3
            if any(tf.location.distance(loc) < MIN_SPAWN_SEPARATION_M * 0.7 for loc in reserved):
                continue
            actor = self.world.try_spawn_actor(bp.find(name), tf)
            if actor is None:
                continue
            reserved.append(carla.Location(tf.location.x, tf.location.y, tf.location.z))
            actor.set_simulate_physics(True)
            actor.set_enable_gravity(True)
            actor.set_autopilot(True, self.tm_port)
            self.tm.ignore_lights_percentage(actor, 100.0)
            self.tm.ignore_signs_percentage(actor, 100.0)
            self.tm.ignore_vehicles_percentage(actor, random.uniform(20.0, 40.0))
            self.tm.auto_lane_change(actor, True)
            self.tm.random_left_lanechange_percentage(actor, 40.0)
            self.tm.random_right_lanechange_percentage(actor, 40.0)
            self.tm.vehicle_percentage_speed_difference(actor, speed_difference)
            self.tm.distance_to_leading_vehicle(actor, random.uniform(1.0, 2.5))
            next_trigger = None
            if side is not None:
                next_trigger = SCENARIO_WARMUP_S + random.uniform(2.0, 5.0)
            item = {"actor": actor, "direction": direction, "released": True,
                    "side": side, "next_trigger_time": next_trigger}
            self.lane_traffic.append(item)
            if direction == "overtaker" and self.overtaker is None:
                self.overtaker = actor
            print(f"[SETUP] SAME_LANE {direction} actor={actor.id} side={side} distance={distance}m "
                  f"speed_diff={speed_difference}%", flush=True)

    def _update_same_lane_traffic(self) -> None:
        """Periodically force overtakers to cut past the ego, alternating left/right."""
        if not self.ego or not self.ego.is_alive: return
        for item in self.lane_traffic:
            if item["direction"] != "overtaker" or item["next_trigger_time"] is None:
                continue
            actor = item["actor"]
            if not actor.is_alive: continue
            if self.sim_time < item["next_trigger_time"]:
                continue
            gap = actor.get_location().distance(self.ego.get_location())
            if gap < OVERTAKE_GAP_TRIGGER_M:
                try:
                    cut_left = item["side"] == "left"
                    self.tm.force_lane_change(actor, cut_left)
                    item["next_trigger_time"] = self.sim_time + random.uniform(
                        OVERTAKE_RETRIGGER_MIN_S, OVERTAKE_RETRIGGER_MAX_S)
                    print(f"[RUNTIME] OVERTAKE_CUT actor={actor.id} side={item['side']} gap={gap:.1f}m "
                          f"ego_turning={self._is_ego_turning()}", flush=True)
                except RuntimeError as exc:
                    print(f"[RUNTIME][WARN] overtaker lane change failed: {exc}", flush=True)

    def _spawn_potholes(self, bp) -> None:
        pothole_bps = []
        for name in ["static.prop.dirtdebris01", "static.prop.dirtdebris02",
                     "static.prop.dirtdebris03", "static.prop.tire"]:
            try:
                pothole_bps.append(bp.find(name))
            except IndexError:
                pass
        if not pothole_bps:
            pothole_bps = list(bp.filter("static.prop.dirtdebris*")) + list(bp.filter("static.prop.tire*"))
        if not pothole_bps or not self.junction: return

        waypoints = self.map.generate_waypoints(6.0)
        junction_loc = self.junction.bounding_box.location
        close_wps = [wp for wp in waypoints if wp.transform.location.distance(junction_loc) < POTHOLE_SEARCH_RADIUS_M]
        sample_wps = random.sample(close_wps, min(POTHOLE_COUNT, len(close_wps)))

        for wp in sample_wps:
            right = wp.transform.get_right_vector()
            side = random.uniform(-1.2, 1.2)
            tf = carla.Transform(wp.transform.location, wp.transform.rotation)
            tf.location.x += right.x * side
            tf.location.y += right.y * side
            tf.location.z += 0.05
            prop = self.world.try_spawn_actor(random.choice(pothole_bps), tf)
            if prop:
                # kept static -- these are pothole/debris markers, not loose objects to roll away
                prop.set_simulate_physics(False)
                self.static_props.append(prop)

    def _spawn_pushcart(self, bp) -> None:
        if not self.ego_entry_wp: return
        cart_bp = bp.find("vehicle.micro.microlino")
        old = self.ego_entry_wp.previous(PUSHCART_BACKOFF_M)
        wp = old[0] if old else self.ego_entry_wp
        tf = wp.transform; right = tf.get_right_vector()
        tf.location.x += right.x * 2.2; tf.location.y += right.y * 2.2; tf.location.z += 0.2
        tf.rotation.yaw += 20.0
        self.pushcart = self.world.try_spawn_actor(cart_bp, tf)
        if self.pushcart: self.pushcart.set_simulate_physics(False)

    def _spawn_weave_bike(self, bp) -> None:
        old = self.ego_entry_wp.previous(20.0)
        wp = old[0] if old else self.ego_entry_wp
        bike_bp = bp.find("vehicle.yamaha.yzf")
        tf = wp.transform; tf.location.z += 0.3
        self.weave_bike = self.world.try_spawn_actor(bike_bp, tf)
        if self.weave_bike:
            self.weave_bike.set_simulate_physics(True)
            self.weave_bike.set_enable_gravity(True)
            self.weave_bike.apply_control(carla.VehicleControl(brake=1.0, hand_brake=True))

    # ------------------------------------------------------------------
    # Sudden high-speed bike racers -- spawn behind the ego and blast past
    # from a random side; extra likely to fire while the ego is turning.
    # ------------------------------------------------------------------
    def _spawn_and_launch_racer(self) -> None:
        if not self.ego or not self.ego.is_alive:
            return
        ego_wp = self.map.get_waypoint(self.ego.get_location(), project_to_road=True, lane_type=carla.LaneType.Driving)
        if ego_wp is None:
            return
        behind_dist = random.uniform(RACER_BEHIND_MIN_M, RACER_BEHIND_MAX_M)
        route = ego_wp.previous(behind_dist)
        if not route:
            return
        tf = route[0].transform
        tf.location.z += 0.3
        side = random.choice([-1, 1])  # -1 => overtakes from the left, +1 => from the right
        right = tf.get_right_vector()
        tf.location.x += right.x * side * random.uniform(2.5, 3.2)
        tf.location.y += right.y * side * random.uniform(2.5, 3.2)
        name = random.choice(BIKES)
        actor = self.world.try_spawn_actor(self.bp.find(name), tf)
        if actor is None:
            return
        actor.set_simulate_physics(True)
        actor.set_enable_gravity(True)
        actor.set_autopilot(True, self.tm_port)
        self.tm.ignore_lights_percentage(actor, 100.0)
        self.tm.ignore_signs_percentage(actor, 100.0)
        self.tm.ignore_vehicles_percentage(actor, 60.0)
        self.tm.auto_lane_change(actor, True)
        self.tm.vehicle_percentage_speed_difference(actor, RACER_SPEED_DIFFERENCE)
        self.tm.distance_to_leading_vehicle(actor, 1.0)
        self.racers.append({"actor": actor, "spawn_time": self.sim_time, "side": side})
        print(f"[RUNTIME] RACER_SPAWN actor={actor.id} type={name} side={'left' if side < 0 else 'right'} "
              f"behind={behind_dist:.1f}m ego_turning={self._is_ego_turning()}", flush=True)

    def _maybe_spawn_racer(self) -> None:
        if self.sim_time < self.next_racer_time:
            return
        self._spawn_and_launch_racer()
        cooldown = random.uniform(RACER_SPAWN_COOLDOWN_MIN_S, RACER_SPAWN_COOLDOWN_MAX_S)
        if self._is_ego_turning() and random.random() < RACER_TURN_BONUS_CHANCE:
            cooldown *= RACER_TURN_COOLDOWN_SCALE  # sneak another one in while the ego is mid-turn
        self.next_racer_time = self.sim_time + cooldown

    def _update_racers(self) -> None:
        if not self.ego or not self.ego.is_alive:
            self.racers = []
            return
        survivors = []
        for item in self.racers:
            actor = item["actor"]
            if not actor.is_alive:
                continue
            age = self.sim_time - item["spawn_time"]
            far_ahead = (not self._is_behind_ego(actor.get_location())
                         and actor.get_location().distance(self.ego.get_location()) > 40.0)
            if age > RACER_LIFETIME_S or far_ahead:
                try:
                    actor.destroy()
                except RuntimeError:
                    pass
                continue
            survivors.append(item)
        self.racers = survivors

    @staticmethod
    def _png(image) -> bytes:
        bgra = np.frombuffer(image.raw_data, dtype=np.uint8).reshape(image.height, image.width, 4)
        ok, enc = cv2.imencode(".png", bgra[:, :, :3])
        if not ok: raise RuntimeError("PNG encoding failed")
        return enc.tobytes()

    def _speed(self, actor) -> float:
        v = actor.get_velocity(); return math.sqrt(v.x*v.x + v.y*v.y + v.z*v.z)





    def _print_ground_truth(self, frame):
        print(f"\n[GROUND TRUTH][frame {frame}]", flush=True)

        # Ego
        if self.ego and self.ego.is_alive:
            loc = self.ego.get_location()
            vel = self.ego.get_velocity()
            print(
                f"  EGO actor={self.ego.id} "
                f"pos=({loc.x:.2f},{loc.y:.2f}) "
                f"vel=({vel.x:.2f},{vel.y:.2f}) "
                f"speed={self._speed(self.ego):.2f} m/s",
                flush=True
            )

        # Cross traffic
        for item in self.cross:
            actor = item["actor"]
            if actor.is_alive:
                loc = actor.get_location()
                vel = actor.get_velocity()
                print(
                    f"  CROSS actor={actor.id} type={actor.type_id} "
                    f"pos=({loc.x:.2f},{loc.y:.2f}) "
                    f"vel=({vel.x:.2f},{vel.y:.2f}) "
                    f"speed={self._speed(actor):.2f} m/s",
                    flush=True
                )

        # Same-lane traffic / overtakers
        for item in self.lane_traffic:
            actor = item["actor"]
            if actor.is_alive:
                loc = actor.get_location()
                vel = actor.get_velocity()
                print(
                    f"  LANE actor={actor.id} type={actor.type_id} "
                    f"pos=({loc.x:.2f},{loc.y:.2f}) "
                    f"vel=({vel.x:.2f},{vel.y:.2f}) "
                    f"speed={self._speed(actor):.2f} m/s",
                    flush=True
                )

        # Walkers
        for item in self.walkers:
            actor = item["actor"]
            if actor.is_alive:
                loc = actor.get_location()
                vel = actor.get_velocity()
                print(
                    f"  WALKER actor={actor.id} type={actor.type_id} "
                    f"pos=({loc.x:.2f},{loc.y:.2f}) "
                    f"vel=({vel.x:.2f},{vel.y:.2f}) "
                    f"speed={self._speed(actor):.2f} m/s",
                    flush=True
                )

        # Cattle
        for item in self.cattle:
            actor = item["actor"]
            if actor.is_alive:
                loc = actor.get_location()
                vel = actor.get_velocity()
                print(
                    f"  CATTLE actor={actor.id} "
                    f"pos=({loc.x:.2f},{loc.y:.2f}) "
                    f"vel=({vel.x:.2f},{vel.y:.2f}) "
                    f"speed={self._speed(actor):.2f} m/s",
                    flush=True
                )

        # Racer bikes
        for item in self.racers:
            actor = item["actor"]
            if actor.is_alive:
                loc = actor.get_location()
                vel = actor.get_velocity()
                print(
                    f"  RACER actor={actor.id} type={actor.type_id} "
                    f"pos=({loc.x:.2f},{loc.y:.2f}) "
                    f"vel=({vel.x:.2f},{vel.y:.2f}) "
                    f"speed={self._speed(actor):.2f} m/s",
                    flush=True
                )

        # Weave bike
        if self.weave_bike and self.weave_bike.is_alive:
            loc = self.weave_bike.get_location()
            vel = self.weave_bike.get_velocity()
            print(
                f"  WEAVE_BIKE actor={self.weave_bike.id} "
                f"pos=({loc.x:.2f},{loc.y:.2f}) "
                f"vel=({vel.x:.2f},{vel.y:.2f}) "
                f"speed={self._speed(self.weave_bike):.2f} m/s",
                flush=True
            )
    



    

    def _send_sensors(self, frame, snap) -> None:
        try:
            image = self.rgb_buf.get(frame, SENSOR_WAIT_S)
            lidar = self.lidar_buf.get(frame, SENSOR_WAIT_S)
            radar = self.radar_buf.get(frame, SENSOR_WAIT_S)
            ego_tf = self.ego.get_transform()
            ego_velocity = self.ego.get_velocity()
            self.uploader.submit({
                "frame": frame,
                "timestamp": snap.timestamp.elapsed_seconds,
                "speed": self._speed(self.ego),

                "ego_position": {
                    "x": ego_tf.location.x,
                    "y": ego_tf.location.y,
                    "z": ego_tf.location.z,
                },

                "ego_velocity": {
                    "x": ego_velocity.x,
                    "y": ego_velocity.y,
                    "z": ego_velocity.z,
                },

                "ego_yaw_deg": ego_tf.rotation.yaw,

                "image": self._png(image),
                "lidar": lidar,
                "radar": radar,
            })
        except TimeoutError as exc:
            print(f"[SENSOR][WARN] {exc}", flush=True)

    def _release_cross_traffic(self, ego_loc) -> None:
        if self.sim_time < SCENARIO_WARMUP_S or self.cross_armed: return
        if ego_loc.distance(self.junction.bounding_box.location) > JUNCTION_TRIGGER_DISTANCE_M: return
        self.cross_armed = True
        for index, cv in enumerate(self.cross):
            cv["release_time"] = self.sim_time + index * RELEASE_INTERVAL_S
        print(f"[RUNTIME] armed {len(self.cross)} physics vehicles", flush=True)

    def _update_cross_traffic(self, ego_loc) -> None:
        survivors = []
        for cv in self.cross:
            actor = cv["actor"]
            if not actor.is_alive:
                continue
            if cv["release_time"] is not None:
                if not cv["released"] and self.sim_time >= cv["release_time"]:
                    cv["released"] = True
                    actor.apply_control(carla.VehicleControl(throttle=0.25, brake=0.0, hand_brake=False))
                    print(f"[RUNTIME] RELEASE actor={actor.id} t={self.sim_time:.2f}", flush=True)
                if cv["released"] and self.sim_time - cv["release_time"] > CROSS_CLEAR_TIME_S:
                    actor.apply_control(carla.VehicleControl(throttle=0.0, brake=1.0, hand_brake=False))
            behind = self._is_behind_ego(actor.get_location())
            if behind and ego_loc.distance(actor.get_location()) > CROSS_VEHICLE_DESPAWN_BEHIND_M:
                try:
                    actor.destroy()
                except RuntimeError:
                    pass
                continue
            survivors.append(cv)
        self.cross = survivors

    def _spawn_dynamic_cross_vehicle(self) -> None:
        approaches = self._candidate_approaches()
        if not approaches or not self.ego or not self.ego.is_alive:
            return
        entry, exit_wp = random.choice(approaches)
        is_bike = random.random() < (len(BIKES) / (len(BIKES) + len(CARS)))
        name = random.choice(BIKES if is_bike else CARS)
        back = entry.previous(random.uniform(FIRST_QUEUE_BACKOFF_M, FIRST_QUEUE_BACKOFF_M + QUEUE_SPACING_M))
        if not back:
            return
        tf = back[0].transform
        if is_bike:
            right = tf.get_right_vector(); side = random.uniform(-0.7, 0.7)
            tf.location.x += right.x * side; tf.location.y += right.y * side
        tf.location.z += 0.3
        vehicle_bp = self.bp.find(name)
        vehicle_bp.set_attribute("role_name", "physics_cross_traffic")
        actor = self.world.try_spawn_actor(vehicle_bp, tf)
        if actor is None:
            return
        actor.set_simulate_physics(True)
        actor.set_enable_gravity(True)
        actor.set_autopilot(True, self.tm_port)
        self.tm.ignore_lights_percentage(actor, 100.0)
        self.tm.ignore_signs_percentage(actor, 100.0)
        self.tm.auto_lane_change(actor, True)
        self.tm.random_left_lanechange_percentage(actor, 20.0)
        self.tm.random_right_lanechange_percentage(actor, 20.0)
        self.tm.ignore_vehicles_percentage(actor, random.uniform(35.0, 65.0))
        self.tm.vehicle_percentage_speed_difference(actor, random.uniform(-10.0, 35.0))
        self.tm.distance_to_leading_vehicle(actor, 2.0)
        # Joining flow already in motion -- not part of the initial
        # queue-and-release choreography, so release_time stays None and
        # released=True so _update_cross_traffic never tries to re-release it.
        actor.apply_control(carla.VehicleControl(throttle=0.25, brake=0.0, hand_brake=False))
        self.cross.append({"actor": actor, "entry": entry, "exit": exit_wp,
                           "release_time": None, "released": True,
                           "start": carla.Location(tf.location.x, tf.location.y, tf.location.z)})
        print(f"[RUNTIME] CROSS_VEHICLE_SPAWN actor={actor.id} type={name} at=({tf.location.x:.1f},{tf.location.y:.1f})", flush=True)

    def _maybe_spawn_cross_vehicle(self) -> None:
        if self.sim_time < self.next_cross_vehicle_time:
            return
        active = sum(1 for cv in self.cross if cv["actor"].is_alive)
        if active < CROSS_VEHICLE_MAX_ACTIVE:
            self._spawn_dynamic_cross_vehicle()
        self.next_cross_vehicle_time = self.sim_time + random.uniform(CROSS_VEHICLE_RESPAWN_MIN_S, CROSS_VEHICLE_RESPAWN_MAX_S)

    def _update_walkers(self, ego_loc) -> None:
        if self.sim_time < SCENARIO_WARMUP_S: return
        survivors = []
        for item in self.walkers:
            actor, controller = item["actor"], item["controller"]
            if not actor.is_alive or not controller.is_alive:
                continue
            if not item["started"] and ego_loc.distance(actor.get_location()) < JAYWALK_TRIGGER_DISTANCE_M:
                controller.set_max_speed(WALKER_MAX_SPEED_MPS * random.uniform(0.7, 1.4))
                item["started"] = True
                print(f"[RUNTIME] WALK_START actor={actor.id} target=({item['target'].x:.1f},{item['target'].y:.1f})", flush=True)
            age = self.sim_time - item.get("spawn_time", 0.0)
            behind = self._is_behind_ego(actor.get_location())
            if age > JAYWALK_LIFETIME_S or (behind and ego_loc.distance(actor.get_location()) > JAYWALK_DESPAWN_BEHIND_M):
                try:
                    controller.stop(); controller.destroy(); actor.destroy()
                except RuntimeError:
                    pass
                continue
            survivors.append(item)
        self.walkers = survivors

    def _update_cattle(self, ego_loc) -> None:
        survivors = []
        for item in self.cattle:
            actor, controller = item["actor"], item["controller"]
            if not actor.is_alive or not controller.is_alive:
                continue
            if not item["started"] and ego_loc.distance(actor.get_location()) < CATTLE_TRIGGER_DISTANCE_M:
                controller.set_max_speed(0.35)
                item["started"] = True
                print(f"[RUNTIME] CATTLE_START actor={actor.id}", flush=True)
            age = self.sim_time - item.get("spawn_time", 0.0)
            behind = self._is_behind_ego(actor.get_location())
            if age > CATTLE_LIFETIME_S or (behind and ego_loc.distance(actor.get_location()) > JAYWALK_DESPAWN_BEHIND_M):
                try:
                    controller.stop(); controller.destroy(); actor.destroy()
                except RuntimeError:
                    pass
                continue
            survivors.append(item)
        self.cattle = survivors

    def _update_weave_bike(self, ego_loc) -> None:
        if not self.weave_bike or not self.weave_bike.is_alive: return
        if not self.weave_triggered:
            close_enough = ego_loc.distance(self.weave_bike.get_location()) < WEAVE_TRIGGER_DISTANCE_M
            if not (close_enough and self._is_ego_turning()):
                return
            self.weave_triggered = True
            print(f"[RUNTIME] WEAVE_BIKE_LAUNCH actor={self.weave_bike.id} (ego mid-turn)", flush=True)
        self.weave_elapsed += DT
        speed_mps = self._speed(self.weave_bike)
        target_mps = WEAVE_SPEED_KPH / 3.6
        steer = 0.28 * math.sin(2.0 * math.pi * self.weave_elapsed / WEAVE_PERIOD_S)
        throttle = 0.9 if speed_mps < target_mps else 0.3
        self.weave_bike.apply_control(carla.VehicleControl(throttle=throttle, steer=steer,
                                                            brake=0.0, hand_brake=False))

    def _update_ego_stuck_recovery(self) -> None:
        """No M5 exists yet to slow/stop the ego ahead of a predicted
        conflict, so the ego is expected to collide with cross-traffic --
        but it must not stay wedged against an obstacle for the rest of the
        run. Detected by sustained lack of NET DISPLACEMENT over a trailing
        window, not instantaneous speed: live testing found the ego grinding
        against a locked-contact obstacle reports jittery instantaneous
        speed readings (0.1-0.6+ m/s from collision push-back) that keep
        crossing back above a speed threshold every other tick, which
        constantly reset a naive "speed < threshold" timer and let a
        near-zero-net-progress pileup run indefinitely -- exactly the
        pattern that preceded a CARLA engine crash in live testing (a
        sustained multi-actor collision pileup is a known CARLA/UE4 physics
        stability risk). Net displacement over the full window is immune to
        that per-tick jitter."""
        if not self.ego or not self.ego.is_alive:
            return
        loc = self.ego.get_location()
        if self.ego_stuck_anchor is None:
            self.ego_stuck_anchor = (self.sim_time, loc)
            return
        anchor_time, anchor_loc = self.ego_stuck_anchor
        if self.sim_time - anchor_time >= EGO_STUCK_DURATION_S:
            if loc.distance(anchor_loc) < EGO_STUCK_DISPLACEMENT_M:
                self._respawn_ego_ahead()
                self.ego_stuck_anchor = None
            else:
                self.ego_stuck_anchor = (self.sim_time, loc)

    def _respawn_ego_ahead(self) -> None:
        wp = self.map.get_waypoint(self.ego.get_location(), project_to_road=True, lane_type=carla.LaneType.Driving)
        if wp is None:
            return
        route = wp.next(EGO_RESPAWN_AHEAD_M)
        if not route:
            return
        target = route[0].transform
        target.location.z += 0.3
        self.ego.set_transform(target)
        self.ego.set_target_velocity(carla.Vector3D(0.0, 0.0, 0.0))
        self.ego.set_target_angular_velocity(carla.Vector3D(0.0, 0.0, 0.0))
        print(f"[RUNTIME] EGO_STUCK_RESPAWN ahead={EGO_RESPAWN_AHEAD_M}m t={self.sim_time:.2f}", flush=True)

    def update_spectator(self) -> None:
        if not self.ego or not self.ego.is_alive:
            return
        tf = self.ego.get_transform()
        forward = tf.get_forward_vector()
        up = tf.get_up_vector()
        location = tf.location - forward * 10.0 + up * 5.0
        rotation = carla.Rotation(pitch=-20.0, yaw=tf.rotation.yaw, roll=0.0)
        self.world.get_spectator().set_transform(carla.Transform(location, rotation))

    def step(self) -> None:
        print(f"[TICK] before n={self.frame_count}", flush=True)
        frame = self.world.tick()
        print(f"[TICK] after frame={frame}", flush=True)
        self._print_ground_truth(frame)
        self.update_spectator()
        self.frame_count += 1; self.sim_time += DT
        snap = self.world.get_snapshot(); ego_loc = self.ego.get_location()
        self.trajectory.append({"frame": frame, "t": snap.timestamp.elapsed_seconds,
                                "x": ego_loc.x, "y": ego_loc.y, "z": ego_loc.z})
        self._send_sensors(frame, snap)
        self._release_cross_traffic(ego_loc)
        self._update_cross_traffic(ego_loc)
        self._update_same_lane_traffic()
        self._update_walkers(ego_loc)
        self._update_cattle(ego_loc)
        self._update_weave_bike(ego_loc)
        self._maybe_spawn_jaywalker()
        self._maybe_spawn_cattle_group()
        self._maybe_spawn_racer()
        self._update_racers()
        self._maybe_spawn_cross_vehicle()
        self._update_ego_stuck_recovery()

    def _on_collision(self, event) -> None:
        self.collisions.append({"frame": int(event.frame), "other": event.other_actor.type_id})
        print(f"[COLLISION] frame={event.frame} other={event.other_actor.type_id}", flush=True)

    def finish(self) -> None:
        LOG_DIR.mkdir(exist_ok=True)
        with (LOG_DIR / "scenario2_trajectory.csv").open("w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=["frame", "t", "x", "y", "z"]); writer.writeheader(); writer.writerows(self.trajectory)
        for controller in self.controllers:
            try:
                if controller.is_alive: controller.stop(); controller.destroy()
            except RuntimeError: pass
        for light in self.lights:
            try: light.freeze(False)
            except RuntimeError: pass
        actors = [self.rgb, self.lidar, self.radar, self.collision_sensor, self.ego, self.pushcart, self.weave_bike]
        actors += ([x["actor"] for x in self.cross] + [x["actor"] for x in self.lane_traffic]
                   + [x["actor"] for x in self.walkers] + self.static_props
                   + [x["actor"] for x in self.cattle] + [x["actor"] for x in self.racers])
        for actor in actors:
            try:
                if actor and actor.is_alive: actor.destroy()
            except RuntimeError: pass
        if self.uploader: self.uploader.close()
        if self.world:
            try:
                settings = self.world.get_settings(); settings.synchronous_mode = False; self.world.apply_settings(settings)
                self.tm.set_synchronous_mode(False)
            except RuntimeError: pass
        print(f"[DONE] collisions={len(self.collisions)} frames={self.frame_count}", flush=True)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--host", default="127.0.0.1"); p.add_argument("--port", type=int, default=2000)
    p.add_argument("--ego-spawn-index", type=int, default=10); p.add_argument("--duration", type=float, default=30.0)
    p.add_argument("--m2-url", default=M2_URL); p.add_argument("--tm-port", type=int, default=TM_PORT)
    p.add_argument("--drive-mode", choices=["autopilot", "m5"], default="autopilot",
                   help="'autopilot': CARLA's own Traffic Manager drives the ego (default, used for M2/M3/M4-only "
                        "testing without M5). 'm5': M5_Pipeline's UDP decisions drive the ego via m5_control.py -- "
                        "the SINGLE writer to the ego's control in this mode (spec section 1b); autopilot is never "
                        "enabled at the same time, since two writers fight every tick.")
    args = p.parse_args()
    scenario = Scenario2(args.host, args.port, args.ego_spawn_index, args.m2_url, args.tm_port)
    control_log_file = None
    try:
        scenario.setup()
        if args.drive_mode == "autopilot":
            scenario.ego.set_autopilot(True, scenario.tm_port)
            scenario.tm.vehicle_percentage_speed_difference(scenario.ego, 15.0)
            scenario.tm.ignore_lights_percentage(scenario.ego, 100.0)
            # Moderate value: the ego sometimes fails to avoid crossing/erratic
            # traffic (collides) without being suicidal every single time --
            # M5 doesn't exist yet to actively brake/steer around a predicted
            # conflict, so some collisions are expected (see EGO_STUCK_* recovery).
            scenario.tm.ignore_vehicles_percentage(scenario.ego, 30.0)
            for _ in range(int(args.duration / DT)): scenario.step()
        else:
            from m5_control import M5ControlExecutor
            executor = M5ControlExecutor()
            LOG_DIR.mkdir(exist_ok=True)
            control_log_file = (LOG_DIR / "m5_control_log.jsonl").open("w", encoding="utf-8")
            for _ in range(int(args.duration / DT)):
                scenario.step()
                record = executor.apply(scenario.ego, scenario.world)
                control_log_file.write(json.dumps(record) + "\n")
    except KeyboardInterrupt:
        print("[MAIN] interrupted", flush=True)
    finally:
        if control_log_file is not None:
            control_log_file.close()
        scenario.finish()


if __name__ == "__main__":
    main()

# CARLA 0.9.15 notes:
# - Start the server with a matching 0.9.15 client/server pair.
# - Start a dedicated Traffic Manager on port 8001.
# - Do not run another synchronous client against the same world.
# - If the server stalls, the last [TICK] before line identifies a physics/TM stall.
# - First test with 3 vehicles by temporarily setting roster = roster[:3].
# - Increase to 6, 9, and then 13 only after each smaller test is stable.
# - Chaos knobs to tune per-run: JAYWALK_SUDDEN_CHANCE, JAYWALK_MAX_ACTIVE,
#   CATTLE_MAX_ACTIVE_GROUPS, OVERTAKE_GAP_TRIGGER_M, RACER_SPAWN_COOLDOWN_*,
#   RACER_TURN_BONUS_CHANCE, POTHOLE_COUNT.